### ISSUE TITLE
Make sure all projects use DevOps main branch, sunset others

### ISSUE THREAD

**Issue by teutoburg** [AstarVienna/DevOps#27]
- [x] AstarVienna/ScopeSim_Templates#89
- [x] AstarVienna/speXtra#39
- [x] AstarVienna/HowManyBloodyPhotons#14
- [x] AstarVienna/skycalc_ipy#66
- [x] AstarVienna/astar-utils#37
- [x] AstarVienna/AnisoCADO#13
- [x] AstarVienna/ScopeSim#460
